from tkinter import *
from tkinter import colorchooser
import re
def Hello(event):
    case=nametest.get('1.0',END)
    name=button0.get('1.0',END)
    text=button1.get('1.0',END)
    text+=button2.get('1.0',END)
    text+=button3.get('1.0',END)
    text+=button4.get('1.0',END)
    text+=button5.get('1.0',END)
    text+=button6.get('1.0',END)
    text+=button7.get('1.0',END)
    text+=button8.get('1.0',END)
    text=re.sub('\n',' ',text)
    name=re.sub('\n','',name)
    case=re.sub('\n',' ',case)
    nametest.delete('1.0',END)
    button1.delete('1.0',END)
    button2.delete('1.0',END)
    button3.delete('1.0',END)
    button4.delete('1.0',END)
    button5.delete('1.0',END)
    button6.delete('1.0',END)
    button7.delete('1.0',END)
    button8.delete('1.0',END)
    file=open(name,'a')
    try:
        file.write(case+text)
    finally:
        file.close()
window=Tk()
window.configure(bg="gray")
size=400;
buf=Canvas(window,width=800,height=400)
window.configure(bg="gray")
buf.pack()
#color=colorchooser.askcolor()
but=Button(window,text="Yes",bg="blue",fg="white")
but.bind("<Button-1>",Hello)
but.place(x=300,y=120,width=200,height=50)

#label=Label(window,text="Name of file",bg="blue",fg="black")
namecase=Label(window,text="Name of test",bg="white",fg="black")
#label.place(x=50,y=10,width=100,height=50)
nametest=Text(window,height=1,width=18,font='Arial 14',wrap=WORD)
button0=Text(window,height=1,width=18,font='Arial 14',wrap=WORD)
button1=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button2=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button3=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button4=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button5=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button6=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button7=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
button8=Text(window,height=1,width=7,font='Arial 14',wrap=WORD)
#nametest.place(x=50,y=10)
button0.place(x=300,y=10)
button1.place(x=40,y=60)

button2.place(x=130,y=60)
button3.place(x=220,y=60)
button4.place(x=310,y=60)
button5.place(x=400,y=60)
button6.place(x=490,y=60)
button7.place(x=580,y=60)
button8.place(x=670,y=60)
window.mainloop()

